server:
  port: 8100

spring:
  application:
    name: greeting-service

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'

greeting-service:
  greeting: "Olá"
  default-value: "Mundo"
